# Generated by Django 3.2 on 2021-04-23 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0002_auto_20210423_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0)),
                ('starting_time', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 22, 49, 11, 767566, tzinfo=utc))),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
