# Generated by Django 3.2 on 2021-04-23 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0003_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='content',
        ),
        migrations.AddField(
            model_name='student',
            name='test_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 22, 59, 13, 177803, tzinfo=utc)),
        ),
    ]
