# Generated by Django 3.2 on 2021-04-23 23:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0004_auto_20210423_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tests',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tests',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AsmIDE.student'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 31, 36, 728930, tzinfo=utc)),
        ),
    ]
