# Generated by Django 3.2 on 2021-04-23 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0005_auto_20210423_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 42, 13, 654673, tzinfo=utc)),
        ),
    ]
