# Generated by Django 3.2 on 2021-04-23 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0006_auto_20210423_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='content',
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 46, 43, 876023, tzinfo=utc)),
        ),
    ]
