# Generated by Django 3.2 on 2021-04-23 23:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0007_auto_20210423_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 54, 16, 729554, tzinfo=utc)),
        ),
    ]
