# Generated by Django 3.2 on 2021-04-24 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0008_alter_tests_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 0, 55, 52, 840344, tzinfo=utc)),
        ),
    ]
