# Generated by Django 3.2 on 2021-04-24 01:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0009_alter_tests_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 1, 7, 45, 110539, tzinfo=utc)),
        ),
    ]
