# Generated by Django 3.2 on 2021-04-24 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0010_alter_tests_starting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('first_name', models.CharField(default='', max_length=25)),
                ('family_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 2, 2, 28, 157087, tzinfo=utc)),
        ),
    ]
