# Generated by Django 3.2 on 2021-04-24 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0013_auto_20210424_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='passwd',
            field=models.CharField(default='@add*wshG', max_length=30),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 16, 44, 47, 44067, tzinfo=utc)),
        ),
    ]
