# Generated by Django 3.2 on 2021-04-24 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0014_auto_20210424_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='passwd',
            field=models.CharField(default='@add*wshG', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 17, 39, 41, 4962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
