# Generated by Django 3.2 on 2021-05-07 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0015_auto_20210424_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 23, 48, 19, 928124, tzinfo=utc)),
        ),
    ]
