# Generated by Django 2.2.18 on 2021-05-08 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0019_alter_tests_starting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='tests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AsmIDE.Tests'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 18, 18, 55, 833764, tzinfo=utc)),
        ),
    ]
