# Generated by Django 2.2.18 on 2021-05-09 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AsmIDE', '0020_auto_20210508_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 4, 14, 15, 775600, tzinfo=utc)),
        ),
    ]
